# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-secret
# type: Opaque
# data:
#   NATS_CLIENT_ID: base64_encoded_value_1
#   NATS_URL: base64_encoded_value_2
#   NATS_CLUSTER_ID: base64_encoded_value_3
